---
- hosts: NUC
  remote_user: adwait
  sudo: yes
  tasks:
  - name: reinstall docker
    apt: name=docker.io state=present
  - name: install python-pip
    apt: name=python-pip state=present
  - name: install
    pip: name=docker-py version=0.5.3
